# Generated by Django 6.1 on 2026-08-31 21:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databruce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_event', to='databruce.events')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_song', to='databruce.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bv_entries',
                'managed': True,
                'unique_together': {('song', 'event')},
            },
        ),
        migrations.CreateModel(
            name='EntryComments',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bruceyversion.entries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bv_entry_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryVotes',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_votes', to='bruceyversion.entries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bv_entry_votes',
                'managed': True,
            },
        ),
    ]
