# Generated by Django 6.1 on 2026-09-03 21:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'db_table': 'bv_entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Entry Comments',
                'db_table': 'bv_entry_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryVote',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Entry Votes',
                'db_table': 'bv_entry_votes',
                'managed': True,
            },
        ),
    ]
