# Generated by Django 6.1 on 2026-09-01 13:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bv_entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryComments',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bv_entry_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntryVotes',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bv_entry_votes',
                'managed': True,
            },
        ),
    ]
