# Generated by Django 6.1 on 2026-09-01 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bruceyversion', '0001_initial'),
        ('databruce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_event', to='databruce.events'),
        ),
        migrations.AddField(
            model_name='entries',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_song', to='databruce.songs'),
        ),
        migrations.AddField(
            model_name='entries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycomments',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bruceyversion.entries'),
        ),
        migrations.AddField(
            model_name='entrycomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryvotes',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entry_votes', to='bruceyversion.entries'),
        ),
        migrations.AddField(
            model_name='entryvotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_entry_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entries',
            unique_together={('song', 'event')},
        ),
    ]
