# Generated by Django 5.1.7 on 2025-08-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False, 'ordering': ['id'], 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='songspage',
            options={'managed': False, 'ordering': ['current__event__date'], 'verbose_name_plural': 'songs_page'},
        ),
    ]
