# Generated by Django 5.1.7 on 2025-10-27 02:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'db_table': 'update_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songspagenew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.IntegerField(blank=True, db_column='song_id', null=True)),
                ('num', models.IntegerField(blank=True, db_column='song_num', null=True)),
                ('artist', models.IntegerField(blank=True, db_column='artist_id', null=True)),
                ('artist_name', models.TextField(blank=True, null=True)),
                ('venue', models.IntegerField(blank=True, db_column='venue_id', null=True)),
                ('venue_name', models.TextField(blank=True, db_column='venue', null=True)),
                ('tour', models.IntegerField(blank=True, db_column='tour_id', null=True)),
                ('tour_name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('set_name', models.TextField(blank=True, null=True)),
                ('prev', models.IntegerField(blank=True, db_column='prev_id', null=True)),
                ('prev_name', models.TextField(blank=True, null=True)),
                ('next', models.IntegerField(blank=True, db_column='next_id', null=True)),
                ('next_name', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'songspagenew',
                'managed': False,
            },
        ),
    ]
