# Generated by Django 6.0.2 on 2026-02-25 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='bands',
            name='name',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(db_column='event_id', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='onstage',
            name='band',
            field=models.ForeignKey(blank=True, db_column='band_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='onstage_band', to='databruce.bands'),
        ),
        migrations.AlterField(
            model_name='releasetracks',
            name='release',
            field=models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='release_tracks', to='databruce.releases'),
        ),
        migrations.DeleteModel(
            name='SongsPage',
        ),
    ]
