# Generated by Django 6.1 on 2026-08-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='length',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
