# Generated by Django 6.1 on 2026-08-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setlists',
            constraint=models.CheckConstraint(condition=models.Q(('set_name__in', ['Soundcheck', 'Interview', 'Post-Show', 'Set 1', 'Set 2', 'Encore', 'Pre-Show', 'Show', 'Recording', 'Rehearsal'])), name='valid_set_name'),
        ),
    ]
