# Generated by Django 5.1.7 on 2025-11-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0002_siteupdates_songspagenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.TextField(db_column='event_id')),
                ('song', models.IntegerField(db_column='song_id')),
                ('tour', models.IntegerField(db_column='tour_id')),
                ('num', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'tour_counts',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='setlists',
            options={'managed': False, 'verbose_name_plural': 'setlists'},
        ),
    ]
