# Generated by Django 5.1.7 on 2025-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0002_alter_events_options_alter_songspage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, db_column='to_value', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'updates',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SongsFirstRelease',
        ),
    ]
