# Generated by Django 6.1 on 2026-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0002_alter_songs_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlists',
            name='note',
            field=models.TextField(blank=True, db_column='song_note', default=None, null=True),
        ),
    ]
