# Generated by Django 6.1 on 2026-08-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0003_alter_setlists_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootlegs',
            name='slid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nugsreleases',
            name='nugs_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setlists',
            name='last',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setlists',
            name='next',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setlists',
            name='position',
            field=models.CharField(blank=True, choices=[('', ''), ('Encore Opener', 'Encore Opener'), ('Main Set Closer', 'Main Set Closer'), ('Pre-Show Closer', 'Pre-Show Closer'), ('Pre-Show Opener', 'Pre-Show Opener'), ('Rehearsal Closer', 'Rehearsal Closer'), ('Rehearsal Opener', 'Rehearsal Opener'), ('Set 1 Closer', 'Set 1 Closer'), ('Set 1 Opener', 'Set 1 Opener'), ('Set 2 Closer', 'Set 2 Closer'), ('Set 2 Opener', 'Set 2 Opener'), ('Show Closer', 'Show Closer'), ('Show Opener', 'Show Opener')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setlists',
            name='tour_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setlists',
            name='tour_total',
            field=models.IntegerField(default=0),
        ),
    ]
