# Generated by Django 5.1.7 on 2025-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databruce', '0003_tourcounts_alter_setlists_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnstageBandMembers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'onstage_band_members',
                'managed': False,
            },
        ),
    ]
