name: Deploy Django to DigitalOcean

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Move into the application directory
            cd /home/lilbud/django-databruce

            # Pull the latest changes from GitHub
            git stash
            git pull
            git stash drop

            # Activate the virtual environment
            source .venv/bin/activate

            # Stop Gunicorn
            sudo systemctl stop gunicorn gunicorn.socket
            
            # Remove Old Static
            rm -rf static/
            
            # Remove Local Settings If Present
            rm -rf databruce/config/local.py
            
            # Collect New Static
            ./manage.py collectstatic --noinput
            
            # Reload Gunicorn using systemd
            sudo systemctl restart gunicorn
